# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|  
  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "forwarded_port", guest: 443, host: 443
    config.vm.define "terraformvm" do |terraformvm|
      terraformvm.vm.box = "centos/7"
      terraformvm.vm.hostname = "terraformvm.localhost.com"
      terraformvm.vm.network "private_network", ip: "172.16.0.1"
      terraformvm.vm.provider "virtualbox" do |v|
        v.name = "terraformvm"
        v.memory = 2048
        v.cpus = 2
        # Prevent VirtualBox from interfering with host audio stack
        v.customize ["modifyvm", :id, "--audio", "none"]
      end
    end
end
