apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    NDACowner: narendranath.panda@nokia.com
  labels:
    argocd.argoproj.io/instance: ndac-paas-dev
    k8s-app: edge-collector
  name: edge-collector
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: edge-collector
  serviceName: edge-collector
  template:
    metadata:
      labels:
        k8s-app: edge-collector
    spec:
      containers:
        - env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: 'telegraf:1.15.3'
          name: telegraf-ds
          resources:
            limits:
              memory: 4Gi
            requests:
              memory: 1Gi
          volumeMounts:
            - mountPath: /etc/telegraf
              name: config
        - args:
            - pushgateway
            - "10"
          command:
            - /bin/sh
            - /opt/pushmetric.sh
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: 'registry.prod.srv.da.nsn-rdnet.net/daas/ndac-utility:1.3'
          name: metric-push
          resources:
            limits:
              memory: 250m
            requests:
              memory: 200m
          volumeMounts:
            - mountPath: /opt
              name: push-edge-metric
      volumes:
        - configMap:
            name: push-edge-metric
          name: push-edge-metric
        - configMap:
            name: edge-collector-config
          name: config
