global:
  scrape_interval: 5s

remote_write:
  - url: "http://localhost:8428/api/v1/write"
    queue_config:
      max_samples_per_send: 10000

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets: ['localhost:9090']